// Generated by scripts/sync-photos.mjs — do not edit by hand.
// Run `npm run sync-photos` after changing the contents of public/drinks/.

/** Drink id -> photograph. Anything missing falls back to the vector render. */
export const photos: Record<string, string> = {
  /* Drop files into public/drinks/ and run: npm run sync-photos */
};
