/**
 * Builds lib/photos.ts from whatever is sitting in public/drinks/.
 *
 * Naming convention: the file stem is the drink id, e.g.
 *   public/drinks/brown-sugar-milk-tea.webp  ->  drink "brown-sugar-milk-tea"
 *
 * Run `npm run sync-photos` after adding or removing files. Any drink without
 * a photo keeps rendering the vector art, so the menu is never half-broken
 * while photography is still being shot.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";

const PHOTO_DIR = "public/drinks";
const OUT = "lib/photos.ts";
const ALLOWED = new Set([".webp", ".avif", ".jpg", ".jpeg", ".png"]);

/** Drink ids, read straight out of the menu data so the two cannot drift. */
function drinkIds() {
  const src = readFileSync("lib/drinks.ts", "utf8");
  const start = src.indexOf("export const drinks:");
  if (start === -1) throw new Error("could not find the drinks array in lib/drinks.ts");
  return new Set([...src.slice(start).matchAll(/^ {4}id: "([^"]+)",$/gm)].map((m) => m[1]));
}

const ids = drinkIds();
const files = existsSync(PHOTO_DIR)
  ? readdirSync(PHOTO_DIR).filter((f) => ALLOWED.has(extname(f).toLowerCase()))
  : [];

const map = {};
const unmatched = [];

for (const file of files.sort()) {
  const id = basename(file, extname(file));
  if (ids.has(id)) map[id] = `/drinks/${file}`;
  else unmatched.push(file);
}

const entries = Object.entries(map);
const body = entries.length
  ? entries.map(([id, path]) => `  "${id}": "${path}",`).join("\n")
  : "  /* Drop files into public/drinks/ and run: npm run sync-photos */";

writeFileSync(
  OUT,
  `// Generated by scripts/sync-photos.mjs — do not edit by hand.
// Run \`npm run sync-photos\` after changing the contents of public/drinks/.

/** Drink id -> photograph. Anything missing falls back to the vector render. */
export const photos: Record<string, string> = {
${body}
};
`
);

console.log(`${entries.length}/${ids.size} drinks have a photo -> ${OUT}`);
if (unmatched.length) {
  console.warn(
    `\nIgnored ${unmatched.length} file(s) whose name is not a drink id:\n` +
      unmatched.map((f) => `  ${join(PHOTO_DIR, f)}`).join("\n") +
      `\n\nRename them to <drink-id>.webp. Valid ids are in lib/drinks.ts.`
  );
}
